# Generated by Django 6.1.1 on 2026-09-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('call_status', models.CharField(choices=[('Pending', 'Pending'), ('Connected', 'Connected'), ('Not Connected', 'Not Connected')], default='Pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
