# Generated by Django 6.1.1 on 2026-09-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
