# Generated by Django 6.1.1 on 2026-09-21 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_contact_follow_up_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='follow_up_date',
        ),
    ]
