# Generated by Django 6.1.1 on 2026-09-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_contact_follow_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
