# Generated by Django 6.1.1 on 2026-09-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
