# Generated by Django 6.1.1 on 2026-09-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_contact_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
