# Generated by Django 6.1.1 on 2026-10-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_assign_unowned_contacts_to_sole_telecaller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='call_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Connected', 'Connected'), ('Not Connected', 'Not Connected')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='reminder_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
